app:
  db:
    enable: true
    type: mysql
    host: 192.168.5.129
    port: 3306
    name: upm
    user: root
    password: root-123456
    maxIdleConnection: 10
    maxOpenConnection: 30
    tablePrefix: upm_
